/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Healthz */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Projects */
        get: operations["list_projects_api_projects_get"];
        put?: never;
        /** Create Project */
        post: operations["create_project_api_projects_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Project */
        get: operations["get_project_api_projects__project_id__get"];
        put?: never;
        post?: never;
        /** Delete Project */
        delete: operations["delete_project_api_projects__project_id__delete"];
        options?: never;
        head?: never;
        /** Update Project */
        patch: operations["update_project_api_projects__project_id__patch"];
        trace?: never;
    };
    "/api/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Jobs */
        get: operations["list_jobs_api_jobs_get"];
        put?: never;
        /** Create Job */
        post: operations["create_job_api_jobs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job */
        get: operations["get_job_api_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}/followup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Followup Job */
        post: operations["followup_job_api_jobs__job_id__followup_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stop Job */
        post: operations["stop_job_api_jobs__job_id__stop_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/schedules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Schedules */
        get: operations["list_schedules_api_schedules_get"];
        put?: never;
        /** Create Schedule */
        post: operations["create_schedule_api_schedules_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/schedules/{sched_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Schedule */
        delete: operations["delete_schedule_api_schedules__sched_id__delete"];
        options?: never;
        head?: never;
        /** Update Schedule */
        patch: operations["update_schedule_api_schedules__sched_id__patch"];
        trace?: never;
    };
    "/api/allowlist": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Rules */
        get: operations["list_rules_api_allowlist_get"];
        put?: never;
        /** Create Rule */
        post: operations["create_rule_api_allowlist_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/allowlist/{rule_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Rule */
        delete: operations["delete_rule_api_allowlist__rule_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stream Job */
        get: operations["stream_job_api_jobs__job_id__stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/_codegen/stream-event": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stream Event Schema */
        get: operations["stream_event_schema_api__codegen_stream_event_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AllowlistRuleCreate */
        AllowlistRuleCreate: {
            /** Rule */
            rule: string;
            /** Project Id */
            project_id?: string | null;
        };
        /** AllowlistRuleOut */
        AllowlistRuleOut: {
            /** Id */
            id: string;
            /** Rule */
            rule: string;
            /** Project Id */
            project_id: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** AssistantTextEvent */
        AssistantTextEvent: {
            /** Job Id */
            job_id: string;
            /** Turn */
            turn: number;
            /**
             * Ts
             * Format: date-time
             */
            ts: string;
            /**
             * Seq
             * @default 0
             */
            seq: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "assistant_text";
            /** Text */
            text: string;
        };
        /**
         * AuthInfo
         * @description Returned to authenticated clients on /api/me.
         */
        AuthInfo: {
            /**
             * Ok
             * @default true
             */
            ok: boolean;
        };
        /** FollowupCreate */
        FollowupCreate: {
            /** Prompt */
            prompt: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** JobCreate */
        JobCreate: {
            /** Prompt */
            prompt: string;
            /** Project Id */
            project_id?: string | null;
            /** Title */
            title?: string | null;
        };
        /** JobOut */
        JobOut: {
            /** Id */
            id: string;
            /** Project Id */
            project_id: string;
            /** Title */
            title: string;
            /** Status */
            status: string;
            /** Session Id */
            session_id?: string | null;
            /** Schedule Id */
            schedule_id?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Ended At */
            ended_at?: string | null;
            /** Turns */
            turns?: components["schemas"]["TurnOut"][];
        };
        /** JobStatusEvent */
        JobStatusEvent: {
            /** Job Id */
            job_id: string;
            /** Turn */
            turn: number;
            /**
             * Ts
             * Format: date-time
             */
            ts: string;
            /**
             * Seq
             * @default 0
             */
            seq: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "job_status";
            /**
             * Status
             * @enum {string}
             */
            status: "queued" | "running" | "done" | "failed" | "stopped";
        };
        /** ProjectCreate */
        ProjectCreate: {
            /** Name */
            name: string;
            /** Path */
            path: string;
            /**
             * Permission Mode
             * @default acceptEdits
             * @enum {string}
             */
            permission_mode: "acceptEdits" | "plan" | "default";
            /**
             * Dangerously Skip
             * @default false
             */
            dangerously_skip: boolean;
            /** Extra Claude Args */
            extra_claude_args?: string[];
            /** Idle Timeout Seconds */
            idle_timeout_seconds?: number | null;
            /**
             * Is Default
             * @default false
             */
            is_default: boolean;
        };
        /** ProjectOut */
        ProjectOut: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Path */
            path: string;
            /** Permission Mode */
            permission_mode: string;
            /** Dangerously Skip */
            dangerously_skip: boolean;
            /** Extra Claude Args */
            extra_claude_args?: string[];
            /** Idle Timeout Seconds */
            idle_timeout_seconds?: number | null;
            /**
             * Is Default
             * @default false
             */
            is_default: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ProjectUpdate */
        ProjectUpdate: {
            /** Name */
            name?: string | null;
            /** Path */
            path?: string | null;
            /** Permission Mode */
            permission_mode?: ("acceptEdits" | "plan" | "default") | null;
            /** Dangerously Skip */
            dangerously_skip?: boolean | null;
            /** Extra Claude Args */
            extra_claude_args?: string[] | null;
            /** Idle Timeout Seconds */
            idle_timeout_seconds?: number | null;
            /** Is Default */
            is_default?: boolean | null;
        };
        /** ScheduleCreate */
        ScheduleCreate: {
            /** Project Id */
            project_id: string;
            /** Name */
            name: string;
            /** Cron */
            cron: string;
            /** Prompt */
            prompt: string;
            /**
             * Enabled
             * @default true
             */
            enabled: boolean;
        };
        /** ScheduleOut */
        ScheduleOut: {
            /** Id */
            id: string;
            /** Project Id */
            project_id: string;
            /** Name */
            name: string;
            /** Cron */
            cron: string;
            /** Prompt */
            prompt: string;
            /** Enabled */
            enabled: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ScheduleUpdate */
        ScheduleUpdate: {
            /** Name */
            name?: string | null;
            /** Cron */
            cron?: string | null;
            /** Prompt */
            prompt?: string | null;
            /** Enabled */
            enabled?: boolean | null;
        };
        /** ToolResultEvent */
        ToolResultEvent: {
            /** Job Id */
            job_id: string;
            /** Turn */
            turn: number;
            /**
             * Ts
             * Format: date-time
             */
            ts: string;
            /**
             * Seq
             * @default 0
             */
            seq: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "tool_result";
            /** Ok */
            ok: boolean;
            /**
             * Output Preview
             * @default
             */
            output_preview: string;
        };
        /** ToolUseEvent */
        ToolUseEvent: {
            /** Job Id */
            job_id: string;
            /** Turn */
            turn: number;
            /**
             * Ts
             * Format: date-time
             */
            ts: string;
            /**
             * Seq
             * @default 0
             */
            seq: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "tool_use";
            /** Tool */
            tool: string;
            /** Input */
            input?: {
                [key: string]: unknown;
            };
        };
        /** TurnDoneEvent */
        TurnDoneEvent: {
            /** Job Id */
            job_id: string;
            /** Turn */
            turn: number;
            /**
             * Ts
             * Format: date-time
             */
            ts: string;
            /**
             * Seq
             * @default 0
             */
            seq: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "turn_done";
            /** Exit Code */
            exit_code: number;
            /** Cost Usd */
            cost_usd?: number | null;
            /** Duration Ms */
            duration_ms?: number | null;
        };
        /** TurnOut */
        TurnOut: {
            /** Id */
            id: string;
            /** Idx */
            idx: number;
            /** Prompt */
            prompt: string;
            /** Status */
            status: string;
            /** Exit Code */
            exit_code?: number | null;
            /** Cost Usd */
            cost_usd?: number | null;
            /** Started At */
            started_at?: string | null;
            /** Ended At */
            ended_at?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    me_api_me_get: {
        parameters: {
            query?: {
                token?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthInfo"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_projects_api_projects_get: {
        parameters: {
            query?: {
                token?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_project_api_projects_post: {
        parameters: {
            query?: {
                token?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_project_api_projects__project_id__get: {
        parameters: {
            query?: {
                token?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_project_api_projects__project_id__delete: {
        parameters: {
            query?: {
                token?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_project_api_projects__project_id__patch: {
        parameters: {
            query?: {
                token?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_jobs_api_jobs_get: {
        parameters: {
            query?: {
                token?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_job_api_jobs_post: {
        parameters: {
            query?: {
                token?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JobCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_api_jobs__job_id__get: {
        parameters: {
            query?: {
                token?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    followup_job_api_jobs__job_id__followup_post: {
        parameters: {
            query?: {
                token?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FollowupCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stop_job_api_jobs__job_id__stop_post: {
        parameters: {
            query?: {
                token?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_schedules_api_schedules_get: {
        parameters: {
            query?: {
                token?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScheduleOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_schedule_api_schedules_post: {
        parameters: {
            query?: {
                token?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScheduleCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScheduleOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_schedule_api_schedules__sched_id__delete: {
        parameters: {
            query?: {
                token?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path: {
                sched_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_schedule_api_schedules__sched_id__patch: {
        parameters: {
            query?: {
                token?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path: {
                sched_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScheduleUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScheduleOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_rules_api_allowlist_get: {
        parameters: {
            query?: {
                project_id?: string | null;
                token?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AllowlistRuleOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_rule_api_allowlist_post: {
        parameters: {
            query?: {
                token?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AllowlistRuleCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AllowlistRuleOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_rule_api_allowlist__rule_id__delete: {
        parameters: {
            query?: {
                token?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path: {
                rule_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_job_api_jobs__job_id__stream_get: {
        parameters: {
            query?: {
                last_event_id?: number | null;
                token?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_event_schema_api__codegen_stream_event_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ToolUseEvent"] | components["schemas"]["ToolResultEvent"] | components["schemas"]["AssistantTextEvent"] | components["schemas"]["TurnDoneEvent"] | components["schemas"]["JobStatusEvent"];
                };
            };
        };
    };
}
